name: dualrefine
dependencies:
  - python=3.7
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111
    - torch==1.8.2
    - torchvision==0.9.2
    - tensorboardX==2.6
    - opencv-python==4.7.0.72
    - scikit-image==0.19.3
    - numpy==1.21.6
    - matplotlib==3.5.3
    - termcolor==2.2.0
    - yacs==0.1.8
    - tqdm==4.65.0
    - open3d==0.15.2
    - debugpy